In [1]:
import numpy as np

In [20]:
X = np.random.normal(loc = 1, scale = 10, size = (1000,50))
print(X)

[[-18.81651638 -10.84345947  -8.38178424 ...   2.54867739   1.06642629
   20.0144618 ]
 [  8.17459565  -5.95596425 -13.45237129 ... -21.81185304 -18.22568093
  -11.35355657]
 [ -6.20289999  -4.68790875   7.22646819 ...  -9.32173615   3.5453371
  -16.29389522]
 ...
 [ 12.25154533   4.90355537   4.47469214 ...   9.10946616   2.36869989
    5.94452679]
 [ 15.16386612   1.33559628 -24.9314064  ...   7.41132781  -3.54224237
  -13.5882448 ]
 [-10.07916895  -1.40054158  -5.61096629 ...  -4.52070101  -3.84798298
    5.10366489]]


In [21]:
mean = np.mean(X, axis = 0)
std = np.std(X, axis=0)

In [22]:
X_norm = (X-mean)/std
print(X_norm)

[[-2.01081565 -1.20844185 -0.93064825 ...  0.15416875  0.00365622
   1.93755176]
 [ 0.74154316 -0.70056082 -1.42841594 ... -2.34353499 -1.98490268
  -1.2912953 ]
 [-0.72457008 -0.56879162  0.60157746 ... -1.06291379  0.25917315
  -1.79982592]
 ...
 [ 1.15728107  0.42789941  0.33144203 ...  0.82685142  0.13788975
   0.48927193]
 [ 1.45425852  0.05713716 -2.55528602 ...  0.65274001 -0.47138827
  -1.52132151]
 [-1.11984401 -0.22718691 -0.65864352 ... -0.57066    -0.50290287
   0.40271834]]


In [29]:
Z = np.array([[4,5,0],
            [1,9,3],
            [5,1,1],
            [3,3,3],
            [9,9,9],
            [4,7,1]])
r = np.sum(Z, axis=1)
print(np.nonzero(r>10))
print(np.size(np.nonzero(r>10)))

(array([1, 4, 5]),)
3


In [33]:
first = np.eye(3, dtype = int)
second = np.eye(3, dtype = int)
firstsecond = np.vstack((first, second))
print(firstsecond)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
